### ISSUE TITLE
UI tweaks

### ISSUE THREAD

**Issue by vucalur** [p4r4noj4/octotask#13]
- [x] Cost, Priority, Assignee labels glued together if these properties empty

**Comment by p4r4noj4** [comment]
Not sure what did you mean here, but I think this is done?

**Comment by vucalur** [comment]
It's an issue gathering multiple UI improvements in one place - usu. they are too small to create a separate issue. Yup, this bullet is done, but there will be more to follow :)

**Comment by p4r4noj4** [comment]
There should be new issue for tweaks needed. Let's close this one. :8ball:
