### ISSUE TITLE
Filtering issues

### ISSUE THREAD

**Issue by p4r4noj4** [p4r4noj4/octotask#3]
- [x] by milestone
- [x] by assignee
- [x] by state

(combobox or sth like http://www.bootply.com/l2ChB4vYmC?)

**Comment by vucalur** [comment]
All the code in http://www.bootply.com/l2ChB4vYmC  basically deals with hidding and showing  navs. Too much fuss - we're rather looking for sth reusable (like a library or so)

**Comment by p4r4noj4** [comment]
Let's stay with combobox for now I guess. Unless you find some easy library that takes care of this.

**Comment by vucalur** [comment]
my idea for filtering:
replace `issues` session variable with `allIssues` and `displayedIssues` (alternative name: `filteredIssues`). Keep `allIsues` for performance advantage (instead of querying GH with proper filters every time) and when filers are updated, apply them on `allIssues` and store it in `displayedIssues`.
Fetching issues with GH API is only done when entering repo page and stored in `allIssues`

Any other ideas ?

**Comment by p4r4noj4** [comment]
Sounds fine to me. Issues are quite lighweight for session anyway.

**Comment by vucalur** [comment]
should be easy to implement, but as a Meteor newbie, it never hurts to ask: Do you know of any built-in mechanism or library supporting this ? Like filters in Angular - they would do the job beautifully here

**Comment by p4r4noj4** [comment]
I think that instead of building second collection in session you could have a helper, that does the filtering based on another session variable. So in helper function that returns the list of objects, before returning apply the filtering.

Another way would be to use Collections in mini-mongoDB ( http://docs.meteor.com/#/full/mongo_collection ) on client-side and then use https://github.com/julianmontagna/filter-collections . Or simply by hand like in http://stackoverflow.com/questions/12662715/reactive-collection-query-in-a-template or http://stackoverflow.com/questions/26744857/creating-a-simple-filter-in-meteor

I would stay with simpler use which is using filtering in helper, as we are not persisting the collection on server-side anyway.

**Comment by vucalur** [comment]
I like your first proposition better (same is done in linked SO posts)
