### ISSUE TITLE
Burndown chart

### ISSUE THREAD

**Issue by p4r4noj4** [p4r4noj4/octotask#4]
- per milestone?
  - global?

**Comment by vucalur** [comment]
I introduced a requirement for all milestone issues to have cost estimates to avoid possible bugs

**Comment by vucalur** [comment]
On numerous charts ideal burn and actual burn do not start from the same point. But it's perfectly ok. Explanation:
- **ideal OVER actual on the first day of a milestone:** Some issues were closed on the first day of a milestone (i.e. oldest `created_at` date of all milestone's issues)
- **ideal UNDER actual on the first day of a milestone:** Ideal burn does not start from `totalMilestoneCost` point. It starts from `totalMilestoneCost - idealDailyBurn`: it assumes you should start making some progress on the very first day of a milestone.
  Actual burn, however, may start from `totalMilestoneCost` if no issues were closed on the first day.

Actually they will only start from the same point, if issues with cost totaling exactly `idealDailyBurn` were closed on the first day of a milestone. Happens only in frictionless vacuum.
